export const POSTS_PEDIDO = 'POSTS_PEDIDO'
export const POSTS_EXITO = 'POSTS_EXITO'
export const POSTS_FRACASO = 'POSTS_FRACASO'

export const POST_CREATE_PEDIDO = 'POST_CREATE_PEDIDO'
export const POST_CREATE_EXITO = 'POST_CREATE_EXITO'
export const POST_CREATE_FRACASO = 'POST_CREATE_FRACASO'

export const POST_DELETE_PEDIDO = 'POST_DELETE_PEDIDO'
export const POST_DELETE_EXITO = 'POST_DELETE_EXITO'
export const POST_DELETE_FRACASO = 'POST_DELETE_FRACASO'

export const POST_DETAIL_PEDIDO = 'POST_DETAIL_PEDIDO'
export const POST_DETAIL_EXITO = 'POST_DETAIL_EXITO'
export const POST_DETAIL_FRACASO = 'POST_DETAIL_FRACASO'

export const POST_EDIT_PEDIDO = 'POST_EDIT_PEDIDO'
export const POST_EDIT_EXITO = 'POST_EDIT_EXITO'
export const POST_EDIT_FRACASO = 'POST_EDIT_FRACASO'

